### ISSUE TITLE
Fluentbit log parsing not working

### ISSUE THREAD

**Issue by estahn** [humio/humio-helm-charts#15]
Log parsing for e.g. nginx is currently not working. I would think that's mainly due to the version used.

```
kubectl exec -n devops -it humio-fluentbit-2g2rt -- /bin/bash
root@humio-fluentbit-2g2rt:/# ./fluent-bit/bin/fluent-bit --version
Fluent Bit v0.13.2
```

Looking at the documentation ([here](https://docs.fluentbit.io/manual/v/0.13/filter/kubernetes)) the config option `K8S-Logging.Parser` doesn't exist.

I suggest updating to the latest version of fluentbit.

**Comment by SaaldjorMike** [comment]
Hi @estahn! As far as I can tell from the release notes that specific option was released as part of Fluent Bit v0.13.0. See https://fluentbit.io/announcements/v0.13.0/ which shows:
`Kubernetes: new support of declarative annotations, let Pod's suggest a parser or be excluded from the logging pipeline.`

I suspect that it is not working because a parser is not suggested to fluent bit from your Kubernetes workload spec where you run nginx. Did you use the option to suggest the `nginx` parser? Example is shown here: https://github.com/fluent/fluent-bit-docs/blob/master/filter/kubernetes.md#suggest-a-parser

Would probably also be helpful to note how the `log_format` is configured for your specific nginx instance.

You could also consider ensuring the nginx outputs logs directly in JSON which should be parsed without the need for suggesting the nginx parser. If you use the `kubernetes/ingress-nginx` project, see this: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/configmap.md#log-format-upstream
It should also be fairly easy to leverage the same json log format described in the ingress-nginx documentation for any nginx in case you do not use the `kubernetes/ingress-nginx`.

**Comment by estahn** [comment]
@SaaldjorMike Thanks, I did see all that. I have tried to emulate the behaviour locally. I used `fluent-bit` installed via `brew`, which is currently at `Fluent Bit v0.14.9`.

https://gist.github.com/estahn/59c37412b42d586e2a873e4b2a2cb90f

I was running `fluent-bit` with:

```bash
fluent-bit --verbose -c fluent-bit.conf
```

Then was sending data to it with:

```bash
cat nginx.json | nc 127.0.0.1 5170
```

Multiple permutations of the config and things did not yield in the expected results.

**Comment by estahn** [comment]
If that would work I'm also limited by the static configmap (#14). I'm not able to add a parser, e.g. `k8s-nginx-ingress`.

**Comment by SaaldjorMike** [comment]
@estahn I just tried getting it to parse a few nginx logs using the annotation described in the fluent bit documentation I linked previously which also did not work. Then I spotted this PR https://github.com/fluent/fluent-bit/pull/1273 which seems to work for me. I just pushed a new chart version with that change to the regex, maybe I could get you to test that one?

This was the Kubernetes Deployment spec for the nginx workload I tested with: https://gist.github.com/SaaldjorMike/d66b8af91a71bb6fa40aca5166409f54

That should at least be able to parse the default log format for nginx, then let's keep the other issue open to support adding custom parsers to the fluent bit configuration. It is also worth noting that you can always use regexes directly in your queries in Humio to extract certain data to graph e.g. bytes for requests.

**Comment by estahn** [comment]
@SaaldjorMike I deployed it and added the annotation. I verified in humio with `"kubernetes.annotations.fluentbit_io/parser" = nginx`, but it's still not working. Again, I don't think the current version of fluent-bit is supporting this.

**Comment by SaaldjorMike** [comment]
Alright, interesting. The gist I posted above seems to work for me even if our chart deploys fluent bit 0.13.2, as long as I use the helm chart version (0.1.27) with the regex parser change.

Maybe I could get you to grab the gist I posted, perform a few requests to that nginx container and see if that by any chance works for you?

**Comment by jswoods** [comment]
Do you both mind checking out https://github.com/humio/humio-helm-charts/pull/21? I'm hoping that solves these problems. I also was trying to get the `humio-parser` label working (added an example to the humio statefulset), but it doesn't look like humio is picking up that parser, so I'm not sure if I missed a config option or not. Will need to look into that part more.

**Comment by SaaldjorMike** [comment]
Closing this as it has been stale for more than a year.
